config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]
  def index
    @lists = List.all
  end
  def show
    @bookmark = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/bookmarks/new.html.erb
  <div class="row justify-content-center mt-3">
    <div class="col-4">
      <h3>Bookmark:</h3>
      <div class="container">
          <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, colletion: Movie.all %>
          <%= f.input :comment %>
          <%= f.submit %>
          <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div>
   <nav class="navbar navbar-expand-lg navbar-light bg-light p-3 justify-content-between">
    <div class = "navbar-header justify-content-between">
      <a class="navbar-brand" href="/lists">WatchList</a>
    </div>
      <a class="btn btn-secondary my-2 my-sm-0" href=" /lists/new" >New List</a>
    </nav>
  </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-4">
<h1 class="text-center">WatchList</h1>
<div id="carouselExampleCaptions" class="carousel slide mt-4">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
<% @lists.each do |list| %>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://codetheweb.blog/assets/img/posts/css-advanced-background-images/cover.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5><%= list.name %></h5>
    <%= link_to "Show this list", list %>
      </div>
    </div>
  </div>
      <% end %>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<div class="banner" >
  <div class="container mt-4">
    <h1 class='text-center'><%= @list.name %></h1>
  </div>
</div>

<div class="container mt-4">
<div class="row">
  <div class="col-sm-6">
  <% @bookmark.each do |bookmark| %>
  <div class="card" style="width: 18rem;">
    <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= bookmark.movie.title %></h5>
       <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:" align-items-center " do %>
          <i class="fa-solid fa-trash remove"></i>
        <% end %>
    </div>
  </div>
  </div>
  <% end %>
  </div>
</div>


<div class="container mt-4 text-center">
   <%= link_to "Add a movie", new_list_bookmark_path(@list), class:"btn btn-primary my-4" %>
</div>